import type { Metadata } from "next";
import "./styles/globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="fr">
      <body className="antialiased bg-DarkBlue-900 text-gray-200">
        {children}
      </body>
    </html>
  );
}
